In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your vedios are good']

In [9]:
## Vocabulary size
voc_size = 100

ONE HOT REPRESENTATION

In [10]:
onehot_repr =[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[31, 81, 39, 3], [31, 81, 39, 88], [31, 27, 39, 51], [61, 65, 57, 72, 68], [61, 65, 57, 72, 48], [51, 31, 91, 39, 73], [83, 43, 67, 72]]


Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [8]:
import numpy as np

In [14]:
# if we add pre in padding then it became pre padding
#otherwise it will became post padding

sent_length = 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[ 0  0  0  0 31 81 39  3]
 [ 0  0  0  0 31 81 39 88]
 [ 0  0  0  0 31 27 39 51]
 [ 0  0  0 61 65 57 72 68]
 [ 0  0  0 61 65 57 72 48]
 [ 0  0  0 51 31 91 39 73]
 [ 0  0  0  0 83 43 67 72]]


In [20]:
## 10 Feature Dimensions
dim = 10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             1000      
                                                                 
Total params: 1000 (3.91 KB)
Trainable params: 1000 (3.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
embedded_docs[0]

array([ 0,  0,  0,  0, 31, 81, 39,  3], dtype=int32)

In [24]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 118ms/step


array([[-0.04906122, -0.03834923, -0.01821617, -0.00312984, -0.03943495,
         0.01094077, -0.0102864 ,  0.0414964 , -0.01824591,  0.00266112],
       [-0.04906122, -0.03834923, -0.01821617, -0.00312984, -0.03943495,
         0.01094077, -0.0102864 ,  0.0414964 , -0.01824591,  0.00266112],
       [-0.04906122, -0.03834923, -0.01821617, -0.00312984, -0.03943495,
         0.01094077, -0.0102864 ,  0.0414964 , -0.01824591,  0.00266112],
       [-0.04906122, -0.03834923, -0.01821617, -0.00312984, -0.03943495,
         0.01094077, -0.0102864 ,  0.0414964 , -0.01824591,  0.00266112],
       [ 0.00504675,  0.02607769,  0.00016535, -0.01832166,  0.03745475,
         0.02448631, -0.0247263 , -0.04678985, -0.02982228,  0.01275461],
       [ 0.04297704,  0.02378244, -0.04340032,  0.02629736,  0.00734432,
         0.02864167,  0.02554614, -0.04652305,  0.01676588, -0.02824428],
       [-0.04847974, -0.04769405, -0.04859679, -0.02154949,  0.00288367,
         0.02671042,  0.00311878,  0.02987177

In [25]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 34ms/step
[[[-4.9061216e-02 -3.8349234e-02 -1.8216170e-02 -3.1298399e-03
   -3.9434947e-02  1.0940768e-02 -1.0286402e-02  4.1496400e-02
   -1.8245913e-02  2.6611201e-03]
  [-4.9061216e-02 -3.8349234e-02 -1.8216170e-02 -3.1298399e-03
   -3.9434947e-02  1.0940768e-02 -1.0286402e-02  4.1496400e-02
   -1.8245913e-02  2.6611201e-03]
  [-4.9061216e-02 -3.8349234e-02 -1.8216170e-02 -3.1298399e-03
   -3.9434947e-02  1.0940768e-02 -1.0286402e-02  4.1496400e-02
   -1.8245913e-02  2.6611201e-03]
  [-4.9061216e-02 -3.8349234e-02 -1.8216170e-02 -3.1298399e-03
   -3.9434947e-02  1.0940768e-02 -1.0286402e-02  4.1496400e-02
   -1.8245913e-02  2.6611201e-03]
  [ 5.0467476e-03  2.6077691e-02  1.6535446e-04 -1.8321656e-02
    3.7454750e-02  2.4486307e-02 -2.4726296e-02 -4.6789851e-02
   -2.9822279e-02  1.2754608e-02]
  [ 4.2977039e-02  2.3782436e-02 -4.3400325e-02  2.6297364e-02
    7.3443167e-03  2.8641675e-02  2.5546145e-02 -4.6523046e-02
    1.6765881e-02 -2.8